version: '3.8'

services:
  php:
    build:
      context: ./docker/php
      args:
        INSTALL_XDEBUG: false
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production

  nginx:
    image: nginx:stable-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
